#pragma once
// Generated by cortico-cursor-companion (scripts/generate.mjs) from sprite/companion.json.
// Edit the sprite there and regenerate; the static_asserts below pin the generated data.

#include <array>
#include <cstddef>
#include <cstdint>

namespace pvz::cursorCompanion {

constexpr int kWidth = 24;
constexpr int kHeight = 24;
constexpr int kDrawOffsetX = 20;
constexpr int kDrawOffsetY = 20;
constexpr int kMotionExtent = 1;
constexpr std::size_t kOpaquePaletteColorCount = 6;

struct Rgba {
    std::uint8_t red;
    std::uint8_t green;
    std::uint8_t blue;
    std::uint8_t alpha;
};

// Palette index zero is transparent; indices one through six preserve the source colors.
constexpr std::array<Rgba, kOpaquePaletteColorCount + 1> kPalette{{
    {0, 0, 0, 0},
    {255, 255, 255, 255},
    {143, 211, 255, 255},
    {252, 243, 243, 255},
    {214, 239, 255, 255},
    {77, 155, 230, 255},
    {77, 101, 180, 255},
}};

constexpr std::array<std::array<std::uint8_t, kWidth>, kHeight> kPixelIndices{{
    {{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {{0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {{0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {{0, 0, 0, 2, 0, 0, 0, 1, 1, 1, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {{0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {{0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0}},
    {{0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0}},
    {{0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 2, 2, 2, 0}},
    {{0, 0, 1, 1, 1, 1, 4, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 2, 2, 0, 0}},
    {{0, 0, 1, 1, 1, 1, 4, 3, 1, 1, 1, 1, 4, 3, 1, 1, 1, 1, 2, 2, 5, 2, 0, 0}},
    {{0, 0, 1, 1, 4, 6, 6, 6, 3, 1, 1, 4, 6, 6, 6, 3, 1, 2, 2, 2, 5, 0, 0, 0}},
    {{0, 0, 1, 1, 6, 2, 1, 5, 3, 1, 4, 3, 2, 1, 5, 6, 2, 2, 5, 5, 2, 2, 2, 0}},
    {{0, 0, 1, 4, 1, 2, 2, 5, 3, 3, 1, 3, 2, 2, 5, 1, 4, 1, 2, 2, 5, 2, 0, 0}},
    {{0, 0, 4, 4, 3, 1, 2, 1, 3, 3, 3, 3, 1, 2, 1, 3, 4, 2, 2, 5, 0, 0, 0, 0}},
    {{0, 0, 0, 4, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 5, 2, 2, 2, 0, 0, 0}},
    {{0, 0, 0, 4, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0}},
    {{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
}};

struct AnimationFrame {
    std::int8_t xOffset;
    std::int8_t yOffset;
    std::uint16_t durationMs;
};

constexpr std::array<AnimationFrame, 4> kIdleFrames{{
    {0, 0, 280},
    {0, -1, 180},
    {1, -1, 320},
    {0, 0, 180},
}};

constexpr std::array<AnimationFrame, 4> kMovingFrames{{
    {0, 0, 60},
    {1, -1, 60},
    {0, -1, 60},
    {-1, 0, 60},
}};

constexpr std::array<AnimationFrame, 3> kPressedFrames{{
    {0, 0, 45},
    {0, 1, 75},
    {0, 1, 120},
}};

constexpr std::array<AnimationFrame, 2> kReleasedFrames{{
    {0, 0, 55},
    {0, -1, 75},
}};

constexpr bool kIdleLoops = true;
constexpr bool kMovingLoops = true;
constexpr bool kPressedLoops = false;
constexpr bool kReleasedLoops = false;

constexpr std::uint64_t Fnv1aByte(std::uint64_t hash, std::uint8_t value) {
    return (hash ^ value) * 1099511628211ULL;
}

constexpr std::uint64_t PixelAssetHash() {
    std::uint64_t hash = 14695981039346656037ULL;
    for (const auto& color : kPalette) {
        hash = Fnv1aByte(hash, color.red);
        hash = Fnv1aByte(hash, color.green);
        hash = Fnv1aByte(hash, color.blue);
        hash = Fnv1aByte(hash, color.alpha);
    }
    for (const auto& row : kPixelIndices) {
        for (const auto index : row) hash = Fnv1aByte(hash, index);
    }
    return hash;
}

constexpr std::size_t OpaquePixelCount() {
    std::size_t count = 0;
    for (const auto& row : kPixelIndices) {
        for (const auto index : row) {
            if (index != 0) ++count;
        }
    }
    return count;
}

constexpr bool PixelIndicesValid() {
    for (const auto& row : kPixelIndices) {
        for (const auto index : row) {
            if (index >= kPalette.size()) return false;
        }
    }
    return true;
}

template <std::size_t FrameCount>
constexpr std::uint32_t AnimationDurationMs(
    const std::array<AnimationFrame, FrameCount>& frames) {
    std::uint32_t duration = 0;
    for (const auto& frame : frames) duration += frame.durationMs;
    return duration;
}

constexpr std::uint64_t kPixelAssetFnv1a64 = PixelAssetHash();

static_assert(sizeof(Rgba) == 4);
static_assert(kPixelAssetFnv1a64 == 0x4BEC0474DB0E5A75ULL);
static_assert(OpaquePixelCount() == 210);
static_assert(PixelIndicesValid());
static_assert(AnimationDurationMs(kIdleFrames) == 960);
static_assert(AnimationDurationMs(kMovingFrames) == 240);
static_assert(AnimationDurationMs(kPressedFrames) == 240);
static_assert(AnimationDurationMs(kReleasedFrames) == 130);

}  // namespace pvz::cursorCompanion
