/**
 * sprite/companion.json + pointer/pointer.json → generated/。
 *
 *   node cursor-companion/scripts/generate.mjs          写出 generated/ 下的全部产物
 *   node cursor-companion/scripts/generate.mjs --check  只比对,产物与源不一致时退出码 1
 *
 * 产物:
 *   cursor_companion.h   C++17 头文件,src/native/implant.cpp 直接 #include 它
 *   companion.svg        每个不透明像素一个 <rect>,cortico-world-canvas 的网页光标用它
 *   companion.png        24×24 原尺寸
 *   companion@8x.png     192×192,最近邻放大,给文档预览
 *   pointer.svg          指针 + 伙伴的 1:1 合成图,按 pointer.json 画
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { deflateSync } from 'node:zlib';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const sprite = JSON.parse(readFileSync(join(root, 'sprite', 'companion.json'), 'utf8'));
const pointer = JSON.parse(readFileSync(join(root, 'pointer', 'pointer.json'), 'utf8'));
const check = process.argv.includes('--check');
const ORIGIN = 'cursor-companion/scripts/generate.mjs';

// ---------------------------------------------------------------------------
// 校验源数据

const { width, height, palette, pixels, animations, drawOffset, motionExtent } = sprite;
if (pixels.length !== height) throw new Error(`pixels 要有 ${height} 行,现在 ${pixels.length} 行`);
const indices = pixels.map((row, y) => {
  if (row.length !== width) throw new Error(`第 ${y} 行要有 ${width} 个字符`);
  return [...row].map((ch) => {
    const index = ch === '.' ? 0 : Number(ch);
    if (!Number.isInteger(index) || index < 0 || index >= palette.length) throw new Error(`第 ${y} 行有非法索引「${ch}」`);
    return index;
  });
});
const rgba = palette.map((hex) => {
  const m = /^#([0-9a-f]{6})([0-9a-f]{2})?$/i.exec(hex);
  if (!m) throw new Error(`调色板颜色格式不对: ${hex}`);
  const v = parseInt(m[1], 16);
  return [(v >> 16) & 255, (v >> 8) & 255, v & 255, m[2] === undefined ? 255 : parseInt(m[2], 16)];
});
if (rgba[0][3] !== 0) throw new Error('调色板第 0 项必须是透明色');
for (const [name, anim] of Object.entries(animations)) {
  for (const frame of anim.frames) {
    if (frame.length !== 3 || frame.some((n) => !Number.isInteger(n))) throw new Error(`动画 ${name} 的帧要是 [dx, dy, ms]`);
    if (Math.abs(frame[0]) > motionExtent || Math.abs(frame[1]) > motionExtent) throw new Error(`动画 ${name} 的位移超出 motionExtent`);
  }
}

// ---------------------------------------------------------------------------
// 派生量:与头文件里的 static_assert 一致

const opaqueCount = indices.flat().filter((i) => i !== 0).length;
const fnv1a = () => {
  let hash = 14695981039346656037n;
  const mix = (byte) => { hash = ((hash ^ BigInt(byte)) * 1099511628211n) & 0xffffffffffffffffn; };
  for (const c of rgba) for (const v of c) mix(v);
  for (const row of indices) for (const i of row) mix(i);
  return hash;
};
const assetHash = fnv1a();
const duration = (frames) => frames.reduce((sum, f) => sum + f[2], 0);
const cap = (s) => s[0].toUpperCase() + s.slice(1);

// ---------------------------------------------------------------------------
// cursor_companion.h

function header() {
  const lines = [];
  const push = (s = '') => lines.push(s);
  push('#pragma once');
  push(`// Generated by ${ORIGIN} from cursor-companion/sprite/companion.json.`);
  push('// Edit the sprite there and regenerate; the static_asserts below pin the generated data.');
  push();
  push('#include <array>');
  push('#include <cstddef>');
  push('#include <cstdint>');
  push();
  push('namespace pvz::cursorCompanion {');
  push();
  push(`constexpr int kWidth = ${width};`);
  push(`constexpr int kHeight = ${height};`);
  push(`constexpr int kDrawOffsetX = ${drawOffset[0]};`);
  push(`constexpr int kDrawOffsetY = ${drawOffset[1]};`);
  push(`constexpr int kMotionExtent = ${motionExtent};`);
  push(`constexpr std::size_t kOpaquePaletteColorCount = ${palette.length - 1};`);
  push();
  push('struct Rgba {');
  push('    std::uint8_t red;');
  push('    std::uint8_t green;');
  push('    std::uint8_t blue;');
  push('    std::uint8_t alpha;');
  push('};');
  push();
  push('// Palette index zero is transparent; indices one through six preserve the source colors.');
  push('constexpr std::array<Rgba, kOpaquePaletteColorCount + 1> kPalette{{');
  for (const c of rgba) push(`    {${c.join(', ')}},`);
  push('}};');
  push();
  push('constexpr std::array<std::array<std::uint8_t, kWidth>, kHeight> kPixelIndices{{');
  for (const row of indices) push(`    {{${row.join(', ')}}},`);
  push('}};');
  push();
  push('struct AnimationFrame {');
  push('    std::int8_t xOffset;');
  push('    std::int8_t yOffset;');
  push('    std::uint16_t durationMs;');
  push('};');
  for (const [name, anim] of Object.entries(animations)) {
    push();
    push(`constexpr std::array<AnimationFrame, ${anim.frames.length}> k${cap(name)}Frames{{`);
    for (const f of anim.frames) push(`    {${f.join(', ')}},`);
    push('}};');
  }
  push();
  for (const [name, anim] of Object.entries(animations)) push(`constexpr bool k${cap(name)}Loops = ${anim.loops};`);
  push();
  push('constexpr std::uint64_t Fnv1aByte(std::uint64_t hash, std::uint8_t value) {');
  push('    return (hash ^ value) * 1099511628211ULL;');
  push('}');
  push();
  push('constexpr std::uint64_t PixelAssetHash() {');
  push('    std::uint64_t hash = 14695981039346656037ULL;');
  push('    for (const auto& color : kPalette) {');
  push('        hash = Fnv1aByte(hash, color.red);');
  push('        hash = Fnv1aByte(hash, color.green);');
  push('        hash = Fnv1aByte(hash, color.blue);');
  push('        hash = Fnv1aByte(hash, color.alpha);');
  push('    }');
  push('    for (const auto& row : kPixelIndices) {');
  push('        for (const auto index : row) hash = Fnv1aByte(hash, index);');
  push('    }');
  push('    return hash;');
  push('}');
  push();
  push('constexpr std::size_t OpaquePixelCount() {');
  push('    std::size_t count = 0;');
  push('    for (const auto& row : kPixelIndices) {');
  push('        for (const auto index : row) {');
  push('            if (index != 0) ++count;');
  push('        }');
  push('    }');
  push('    return count;');
  push('}');
  push();
  push('constexpr bool PixelIndicesValid() {');
  push('    for (const auto& row : kPixelIndices) {');
  push('        for (const auto index : row) {');
  push('            if (index >= kPalette.size()) return false;');
  push('        }');
  push('    }');
  push('    return true;');
  push('}');
  push();
  push('template <std::size_t FrameCount>');
  push('constexpr std::uint32_t AnimationDurationMs(');
  push('    const std::array<AnimationFrame, FrameCount>& frames) {');
  push('    std::uint32_t duration = 0;');
  push('    for (const auto& frame : frames) duration += frame.durationMs;');
  push('    return duration;');
  push('}');
  push();
  push('constexpr std::uint64_t kPixelAssetFnv1a64 = PixelAssetHash();');
  push();
  push('static_assert(sizeof(Rgba) == 4);');
  push(`static_assert(kPixelAssetFnv1a64 == 0x${assetHash.toString(16).toUpperCase().padStart(16, '0')}ULL);`);
  push(`static_assert(OpaquePixelCount() == ${opaqueCount});`);
  push('static_assert(PixelIndicesValid());');
  for (const [name, anim] of Object.entries(animations)) {
    push(`static_assert(AnimationDurationMs(k${cap(name)}Frames) == ${duration(anim.frames)});`);
  }
  push();
  push('}  // namespace pvz::cursorCompanion');
  return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// SVG

const hex6 = (c) => '#' + c.slice(0, 3).map((v) => v.toString(16).padStart(2, '0')).join('');

function spriteRects(offsetX = 0, offsetY = 0) {
  const out = [];
  indices.forEach((row, y) => row.forEach((index, x) => {
    if (index) out.push(`<rect x="${x + offsetX}" y="${y + offsetY}" width="1" height="1" fill="${hex6(rgba[index])}"/>`);
  }));
  return out;
}

function companionSvg() {
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" shape-rendering="crispEdges">`,
    `<!-- Generated by cortico-world-pvz ${ORIGIN}; edit the sprite there. -->`,
    ...spriteRects(),
    '</svg>',
  ].join('\n') + '\n';
}

function pointerSvg() {
  const [hx, hy] = pointer.preview.hotspot;
  const size = pointer.preview.size;
  const arrow = pointer.arrow.points.map(([x, y]) => `${hx + x},${hy + y}`).join(' ');
  const line = pointer.accent.line;
  const [cx, cy] = sprite.drawOffset;
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" width="${size * 4}" height="${size * 4}">`,
    `<!-- Generated by ${ORIGIN} from pointer/pointer.json and sprite/companion.json. -->`,
    `<polygon points="${arrow}" fill="${pointer.arrow.fill}" stroke="${pointer.arrow.outline}" stroke-width="${pointer.arrow.outlineWidth}" stroke-linejoin="miter"/>`,
    `<line x1="${hx + line.from[0]}" y1="${hy + line.from[1]}" x2="${hx + line.to[0]}" y2="${hy + line.to[1]}" stroke="${pointer.accent.color}" stroke-width="${pointer.accent.width}"/>`,
    `<g shape-rendering="crispEdges">`,
    ...spriteRects(hx + cx, hy + cy),
    '</g>',
    '</svg>',
  ].join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// PNG(无依赖:zlib + 自己拼 chunk)

const crcTable = new Uint32Array(256).map((_, n) => {
  let c = n;
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c >>> 0;
});
function crc32(buf) {
  let c = 0xffffffff;
  for (const b of buf) c = crcTable[(c ^ b) & 255] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}
function chunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, 'latin1'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([len, body, crc]);
}
function png(scale) {
  const w = width * scale;
  const h = height * scale;
  const raw = Buffer.alloc((w * 4 + 1) * h);
  for (let y = 0; y < h; y++) {
    const rowStart = y * (w * 4 + 1);
    raw[rowStart] = 0;
    for (let x = 0; x < w; x++) {
      const c = rgba[indices[Math.floor(y / scale)][Math.floor(x / scale)]];
      raw.set(c, rowStart + 1 + x * 4);
    }
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(w, 0);
  ihdr.writeUInt32BE(h, 4);
  ihdr[8] = 8; ihdr[9] = 6; ihdr[10] = 0; ihdr[11] = 0; ihdr[12] = 0;
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

// ---------------------------------------------------------------------------

const outputs = {
  'cursor_companion.h': Buffer.from(header(), 'utf8'),
  'companion.svg': Buffer.from(companionSvg(), 'utf8'),
  'companion.png': png(1),
  'companion@8x.png': png(8),
  'pointer.svg': Buffer.from(pointerSvg(), 'utf8'),
};

const outDir = join(root, 'generated');
mkdirSync(outDir, { recursive: true });
let stale = 0;
for (const [name, bytes] of Object.entries(outputs)) {
  const path = join(outDir, name);
  const same = existsSync(path) && readFileSync(path).equals(bytes);
  if (check) {
    console.log(`${same ? '  ok   ' : '  STALE'} generated/${name}`);
    if (!same) stale++;
  } else {
    writeFileSync(path, bytes);
    console.log(`  wrote generated/${name} (${bytes.length} bytes)`);
  }
}
console.log(`asset hash 0x${assetHash.toString(16).toUpperCase()}, ${opaqueCount} opaque pixels`);
if (check && stale) {
  console.error(`${stale} 个产物与源不一致,运行 node cursor-companion/scripts/generate.mjs 重新生成`);
  process.exit(1);
}
